---
title: "PTR Testes Figures"
author: "Megan Elcheikhali, Advised by Dr. Alex Franks"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(GO.db)
library(tidyverse)
library(patchwork)
library(colorspace)
library(viridis)
source("scripts/plot_functions.R")
source("scripts/go_functions.R")
clusters = c("EC", "LC", "PTM", "SPC", "SPG", "St")
```

## Significant Groups: Observed and Model Fit Values

```{r fig4, echo = FALSE, warning = FALSE, message = FALSE, fig.width = 35, fig.height = 50, results='asis'}
# FIGURE 4: Evaluating posterior samples of mu and r
mrna_colors = colorspace::sequential_hcl(5, palette = "Plasma")[3]
protein_colors = colorspace::sequential_hcl(5, palette = "Viridis")[2]

load("model_output/go_test_results_mean.RData")
go_select = test_res %>% 
  filter(significant == TRUE) %>%
  pull(GO) %>% 
  unique()
go_select = go_select[-6]

GO_rec = AnnotationDbi::select(org.Hs.eg.db, keys = go_select, keytype = "GO", columns = c("UNIPROT", "SYMBOL")) %>% 
         dplyr::select(c(GO, UNIPROT, SYMBOL))
TERM_rec = test_res %>% dplyr::group_by(GO) %>% dplyr::summarise(TERM = unique(TERM))

load("model_output/observed_z.RData")
mrna_pop1_z = mrna_pop1_z %>% merge(GO_rec) %>% dplyr::group_by(GO, ct) %>% 
  dplyr::summarise(mrna_zscore = mean(mrna_zscore, na.rm = T)) %>% merge(TERM_rec) 
mrna_pop2_z = mrna_pop2_z %>% merge(GO_rec) %>% dplyr::group_by(GO, ct) %>% 
  dplyr::summarise(mrna_zscore = mean(mrna_zscore, na.rm = T)) %>% merge(TERM_rec)

protein_pop1_z = protein_pop1_z %>% merge(GO_rec) %>% dplyr::group_by(GO, ct) %>% 
  dplyr::summarise(protein_zscore = mean(protein_zscore, na.rm = T)) %>% merge(TERM_rec)
protein_pop2_z = protein_pop2_z %>% merge(GO_rec) %>% dplyr::group_by(GO, ct) %>% 
  dplyr::summarise(protein_zscore = mean(protein_zscore, na.rm = T)) %>% merge(TERM_rec)
protein_pop3_z = protein_pop3_z %>% merge(GO_rec) %>% dplyr::group_by(GO, ct) %>% 
  dplyr::summarise(protein_zscore = mean(protein_zscore, na.rm = T)) %>% merge(TERM_rec)
protein_pop4_z = protein_pop4_z %>% merge(GO_rec) %>% dplyr::group_by(GO, ct) %>% 
  dplyr::summarise(protein_zscore = mean(protein_zscore, na.rm = T)) %>% merge(TERM_rec)

p = list()
for(i in 1:length(go_select)){
 p[[i]] = plot_zscore_groups(mrna_z = list(mrna_pop1_z, mrna_pop2_z), 
                       protein_z = list(protein_pop1_z, protein_pop2_z, protein_pop3_z, protein_pop4_z), 
                       test_res = test_res, go = go_select[i], clusters = clusters, 
                       mrna_pop_label = c("Pop1", "Pop2"), protein_pop_label = c("Pop1", "Pop2", "Pop3", "Pop4"),
                       mrna_color = mrna_colors, protein_color = protein_colors) +
   xlab("")
}

p
```
